name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        experimental: [false]
        php-version:
          - 7.1
#          - 7.2
#          - 7.3
#          - 7.4
#          - 8.0
        dependencies:
          - highest
        include:
          - php-version: 7.1
            dependencies: lowest
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          ini-values: zend.assertions=1

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Creating build/logs directory
        run: mkdir -p build/logs

      - name: Run PHPUnit
        run: vendor/bin/phpunit --exclude-group=e2e --coverage-clover build/logs/clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v


