name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        experimental: [ false ]
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
          - 8.2
        dependencies:
          - highest
        include:
          - php-version: 7.1
            dependencies: lowest
            experimental: true
          - php-version: 8.0
            dependencies: lowest
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          ini-values: zend.assertions=1, assert.exception=1

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit --exclude-group=e2e --coverage-clover=clover.xml

      - name: Upload coverage file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.php-version }}-${{ matrix.dependencies }}
          path: clover.xml

  upload_coverage:
    name: Upload coverage to Coveralls
    runs-on: ubuntu-latest
    needs:
      - phpunit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Download coverage files
        uses: actions/download-artifact@v4.1.7
        with:
          path: build/logs

      - name: Install php-coveralls
        run: composer global require php-coveralls/php-coveralls

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php-coveralls --coverage_clover=build/logs/*/clover.xml -v
